### PR TITLE
TIP-182 Simple booking test

### PR DESCRIPTION
**Pull request by orsk**

### CODE REVIEW

**Comment by williamsh2** [comment]
|`src/test/java/com/bookinggo/bat/booking/BookingTest.java:43`|
|---|
Are you okay with the string being empty?

**Comment by williamsh2** [comment]
What's the value of checking if you know that it's going to be null?

**Comment by orsk** [comment]
Refactor to GeoCity to be consistent with other changes?

**Comment by orsk** [comment]
reason for keeping this?

**Comment by TomHaughton** [comment]
|`src/main/java/com/bookinggo/bat/search/RestAssuredSearchClient.java:28`|
|---|
This limits us to only being able to run happy path tests, as this method is always looking for a 200 response. If you pass invalid search params this method the test will just fail. Although this ticket is only for happy path tests, we still need to take this into account for future tests

**Pull request merged**
